import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "en" | "fr" | "es" | "zh" | "pa";

export const LANGUAGES: { code: Language; label: string; nativeLabel: string; flag: string }[] = [
  { code: "en", label: "English", nativeLabel: "English", flag: "🇨🇦" },
  { code: "fr", label: "French", nativeLabel: "Français", flag: "🇨🇦" },
  { code: "es", label: "Spanish", nativeLabel: "Español", flag: "🌎" },
  { code: "zh", label: "Mandarin", nativeLabel: "中文", flag: "🇨🇳" },
  { code: "pa", label: "Punjabi", nativeLabel: "ਪੰਜਾਬੀ", flag: "🇮🇳" },
];

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

type TranslationMap = Record<string, string>;

const translations: Record<Language, TranslationMap> = {
  en: {
    // Navigation
    "nav.dashboard": "Dashboard",
    "nav.properties": "Properties",
    "nav.applications": "Applications",
    "nav.tenants": "Tenants",
    "nav.finances": "Finances",
    "nav.payments": "Payments",
    "nav.rentCollection": "Rent Collection",
    "nav.financialDashboard": "Financial Dashboard",
    "nav.hstTracker": "HST/GST Tracker",
    "nav.invoices": "Invoices",
    "nav.operations": "Operations",
    "nav.maintenance": "Maintenance",
    "nav.documents": "Documents",
    "nav.ltbForms": "LTB Forms",
    "nav.leaseTemplates": "Lease Templates",
    "nav.notices": "Notices",
    "nav.insights": "Insights",
    "nav.rentalIntelligence": "Rental Intelligence",
    "nav.tenantPassport": "Tenant Passport",
    "nav.analytics": "Analytics",
    "nav.more": "More",
    "nav.messages": "Messages",
    "nav.admin": "Admin",
    "nav.settings": "Settings",
    "nav.growth": "Growth",
    "nav.listingSyndication": "Listing Syndication",
    "nav.depositFree": "Deposit-Free",
    "nav.vendors": "Vendors",
    "nav.rentCredit": "Rent Credit",
    // Common
    "common.search": "Search",
    "common.add": "Add",
    "common.edit": "Edit",
    "common.delete": "Delete",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.close": "Close",
    "common.download": "Download",
    "common.upload": "Upload",
    "common.submit": "Submit",
    "common.back": "Back",
    "common.next": "Next",
    "common.previous": "Previous",
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.success": "Success",
    "common.warning": "Warning",
    "common.info": "Information",
    "common.confirm": "Confirm",
    "common.yes": "Yes",
    "common.no": "No",
    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.welcome": "Welcome back",
    "dashboard.occupancyRate": "Occupancy Rate",
    "dashboard.monthlyRevenue": "Monthly Revenue",
    "dashboard.totalProperties": "Total Properties",
    "dashboard.pendingApplications": "Pending Applications",
    "dashboard.recentActivity": "Recent Activity",
    "dashboard.greeting": "Good evening",
    "dashboard.goodMorning": "Good morning",
    "dashboard.goodAfternoon": "Good afternoon",
    "dashboard.goodEvening": "Good evening",
    "dashboard.applicationsNeedReview": "applications need review",
    "dashboard.overduePayment": "overdue payment",
    "dashboard.revenueThisMonth": "Revenue this month",
    "dashboard.vsLastMonth": "vs last month",
    "dashboard.activeProperties": "Active properties",
    "dashboard.vacantUnits": "Vacant units",
    "dashboard.totalUnitsOccupied": "total units · occupied",
    "dashboard.alerts": "Alerts",
    "dashboard.aiInsights": "AI Insights",
    "dashboard.recentApplications": "Recent Applications",
    "dashboard.score": "Score",
    "dashboard.recommendation": "Recommendation",
    "dashboard.approve": "Approve",
    "dashboard.review": "Review",
    "dashboard.reject": "Reject",
    "dashboard.viewApplication": "View Application",
    "dashboard.propertyPerformance": "Property Performance",
    "dashboard.units": "units",
    "dashboard.revenue": "Revenue",
    "dashboard.riskLevel": "Risk Level",
    "dashboard.low": "Low",
    "dashboard.medium": "Medium",
    "dashboard.high": "High",
    // Properties
    "properties.title": "Properties",
    "properties.addProperty": "Add Property",
    "properties.totalUnits": "Total Units",
    "properties.occupied": "Occupied",
    "properties.vacant": "Vacant",
    "properties.address": "Address",
    "properties.units": "Units",
    "properties.monthlyRent": "Monthly Rent",
    // Applications
    "applications.title": "Applications",
    "applications.pending": "Pending Review",
    "applications.approved": "Approved",
    "applications.rejected": "Rejected",
    "applications.viewDetails": "View Details",
    "applications.applicantName": "Applicant Name",
    "applications.property": "Property",
    "applications.submittedDate": "Submitted",
    // Tenants
    "tenants.title": "Tenants",
    "tenants.active": "Active",
    "tenants.total": "Total Tenants",
    "tenants.name": "Name",
    "tenants.unit": "Unit",
    "tenants.leaseEnd": "Lease End",
    "tenants.rentStatus": "Rent Status",
    // Rent Collection
    "rent.title": "Rent Collection",
    "rent.interac": "Interac e-Transfer",
    "rent.stripe": "Credit/Debit Card",
    "rent.pad": "Pre-Authorized Debit",
    "rent.expected": "Expected",
    "rent.collected": "Collected",
    "rent.pending": "Pending",
    "rent.late": "Late",
    // LTB Forms
    "ltb.title": "Ontario LTB Forms",
    "ltb.compliant": "RTA Compliant",
    "ltb.allForms": "All Forms",
    "ltb.evictionNotices": "Eviction Notices",
    "ltb.rentIncreases": "Rent Increases",
    "ltb.termination": "Termination",
    "ltb.generateForm": "Generate Form",
    "ltb.legalDeadline": "Legal Deadline",
    // Tax Tracker
    "tax.title": "HST/GST Tracker",
    "tax.totalExpenses": "Total Expenses",
    "tax.hstPaid": "HST/GST Paid",
    "tax.deductible": "Deductible Expenses",
    "tax.ytdTotal": "YTD Total",
    "tax.addExpense": "Add Expense",
    "tax.craCompliant": "CRA Compliant",
    // Lease Templates
    "lease.title": "Province Lease Templates",
    "lease.province": "Province",
    "lease.rentGuideline": "Rent Increase Guideline",
    "lease.noticeRequired": "Notice Required",
    "lease.generateLease": "Generate Lease",
    "lease.tenantName": "Tenant Name",
    "lease.monthlyRent": "Monthly Rent (CAD)",
    "lease.leaseStart": "Lease Start Date",
    "lease.leaseTerm": "Lease Term",
    // Settings
    "settings.language": "Language",
    "settings.english": "English",
    "settings.french": "Français",
    "settings.selectLanguage": "Select Language",
    // Notifications
    "notifications.title": "Notifications",
    "notifications.center": "Notification Centre",
    "notifications.unread": "unread",
    "notifications.urgent": "urgent",
    "notifications.all": "All",
    "notifications.highPriority": "High Priority",
    "notifications.markAllRead": "Mark all as read",
    "notifications.viewDetails": "View Details",
    "notifications.delete": "Delete",
    "notifications.new": "New",
    // Messages
    "messages.title": "Messages",
    "messages.center": "Messaging Centre",
    "messages.conversations": "Conversations",
    "messages.search": "Search conversations...",
    "messages.typeMessage": "Type your message...",
    "messages.sendMessage": "Send",
    "messages.attachFile": "Attach file",
    "messages.pinned": "Pinned",
    "messages.starred": "Starred",
    "messages.tenant": "Tenant",
    "messages.landlord": "Landlord",
    "messages.contractor": "Contractor",
    "messages.admin": "Admin",
    // Reports
    "reports.title": "Reports",
    "reports.dashboard": "Reports Dashboard",
    "reports.analytics": "Reports & Analytics",
    "reports.generate": "Generate",
    "reports.download": "Download",
    "reports.financial": "Financial",
    "reports.occupancy": "Occupancy",
    "reports.maintenance": "Maintenance",
    "reports.compliance": "Compliance",
    "reports.monthly": "Monthly",
    "reports.quarterly": "Quarterly",
    "reports.annual": "Annual",
    "reports.lastGenerated": "Last generated",
    "reports.revenue": "Revenue",
    "reports.expenses": "Expenses",
    "reports.netIncome": "Net Income",
    // Financial Dashboard
    "financial.overview": "Financial Overview",
    "financial.dashboard": "Financial Dashboard",
    "financial.totalRevenue": "Total Revenue",
    "financial.netProfit": "Net Profit",
    "financial.totalExpenses": "Total Expenses",
    "financial.profitMargin": "Profit Margin",
    "financial.revenueVsExpenses": "Revenue vs Expenses",
    "financial.comparison": "12-Month Comparison",
    "financial.expenseBreakdown": "Expense Breakdown",
    "financial.propertyPerformance": "Property Performance",
    "financial.profitability": "Profitability by Property",
    "financial.occupancy": "Occupancy",
    "financial.generateInvoice": "Generate Invoice",
    "financial.downloadReport": "Download Report",
    "financial.scheduleReview": "Schedule Review",
    "financial.export": "Export",
    "financial.lastMonths": "Last months",
    "financial.yearToDate": "Year to date",
    // Contractor Marketplace
    "contractor.marketplace": "Contractor Marketplace",
    "contractor.findContractors": "Find Verified Contractors",
    "contractor.allCategories": "All Categories",
    "contractor.plumbing": "Plumbing",
    "contractor.electrical": "Electrical",
    "contractor.hvac": "HVAC",
    "contractor.general": "General",
    "contractor.painting": "Painting",
    "contractor.flooring": "Flooring",
    "contractor.allRatings": "All Ratings",
    "contractor.featured": "Featured",
    "contractor.verified": "Verified",
    "contractor.rating": "Rating",
    "contractor.reviews": "reviews",
    "contractor.completedJobs": "Completed jobs",
    "contractor.responseTime": "Response time",
    "contractor.viewProfile": "View Profile",
    "contractor.contact": "Contact",
    "contractor.insurance": "Insured",
    "contractor.licensed": "Licensed",
    "contractor.backgroundCheck": "Background Check",
  },

  fr: {
    "nav.dashboard": "Tableau de bord",
    "nav.properties": "Propriétés",
    "nav.applications": "Candidatures",
    "nav.tenants": "Locataires",
    "nav.finances": "Finances",
    "nav.payments": "Paiements",
    "nav.rentCollection": "Perception des loyers",
    "nav.financialDashboard": "Tableau financier",
    "nav.hstTracker": "Suivi TPS/TVQ",
    "nav.invoices": "Factures",
    "nav.operations": "Opérations",
    "nav.maintenance": "Entretien",
    "nav.documents": "Documents",
    "nav.ltbForms": "Formulaires TAL",
    "nav.leaseTemplates": "Modèles de bail",
    "nav.notices": "Avis",
    "nav.insights": "Analyses",
    "nav.rentalIntelligence": "Intelligence locative",
    "nav.tenantPassport": "Passeport locataire",
    "nav.analytics": "Analytique",
    "nav.more": "Plus",
    "nav.messages": "Messages",
    "nav.admin": "Administration",
    "nav.settings": "Paramètres",
    "nav.growth": "Croissance",
    "nav.listingSyndication": "Syndication d'annonces",
    "nav.depositFree": "Sans dépôt",
    "nav.vendors": "Fournisseurs",
    "nav.rentCredit": "Crédit loyer",
    "common.search": "Rechercher",
    "common.add": "Ajouter",
    "common.edit": "Modifier",
    "common.delete": "Supprimer",
    "common.save": "Enregistrer",
    "common.cancel": "Annuler",
    "common.close": "Fermer",
    "common.download": "Télécharger",
    "common.upload": "Téléverser",
    "common.submit": "Soumettre",
    "common.back": "Retour",
    "common.next": "Suivant",
    "common.previous": "Précédent",
    "common.loading": "Chargement...",
    "common.error": "Erreur",
    "common.success": "Succès",
    "common.warning": "Avertissement",
    "common.info": "Information",
    "common.confirm": "Confirmer",
    "common.yes": "Oui",
    "common.no": "Non",
    "dashboard.title": "Tableau de bord",
    "dashboard.welcome": "Bon retour",
    "dashboard.occupancyRate": "Taux d'occupation",
    "dashboard.monthlyRevenue": "Revenus mensuels",
    "dashboard.totalProperties": "Total des propriétés",
    "dashboard.pendingApplications": "Candidatures en attente",
    "dashboard.recentActivity": "Activité récente",
    "dashboard.greeting": "Bonsoir",
    "dashboard.goodMorning": "Bonjour",
    "dashboard.goodAfternoon": "Bon après-midi",
    "dashboard.goodEvening": "Bonsoir",
    "dashboard.applicationsNeedReview": "candidatures à examiner",
    "dashboard.overduePayment": "paiement en retard",
    "dashboard.revenueThisMonth": "Revenus ce mois-ci",
    "dashboard.vsLastMonth": "vs le mois dernier",
    "dashboard.activeProperties": "Propriétés actives",
    "dashboard.vacantUnits": "Unités vacantes",
    "dashboard.totalUnitsOccupied": "unités au total · occupé",
    "dashboard.alerts": "Alertes",
    "dashboard.aiInsights": "Analyses IA",
    "dashboard.recentApplications": "Candidatures récentes",
    "dashboard.score": "Score",
    "dashboard.recommendation": "Recommandation",
    "dashboard.approve": "Approuver",
    "dashboard.review": "Examiner",
    "dashboard.reject": "Refuser",
    "dashboard.viewApplication": "Voir la candidature",
    "dashboard.propertyPerformance": "Performance des propriétés",
    "dashboard.units": "unités",
    "dashboard.revenue": "Revenus",
    "dashboard.riskLevel": "Niveau de risque",
    "dashboard.low": "Faible",
    "dashboard.medium": "Moyen",
    "dashboard.high": "Élevé",
    "properties.title": "Propriétés",
    "properties.addProperty": "Ajouter une propriété",
    "properties.totalUnits": "Total des unités",
    "properties.occupied": "Occupées",
    "properties.vacant": "Vacantes",
    "properties.address": "Adresse",
    "properties.units": "Unités",
    "properties.monthlyRent": "Loyer mensuel",
    "applications.title": "Candidatures",
    "applications.pending": "En attente d'examen",
    "applications.approved": "Approuvées",
    "applications.rejected": "Refusées",
    "applications.viewDetails": "Voir les détails",
    "applications.applicantName": "Nom du candidat",
    "applications.property": "Propriété",
    "applications.submittedDate": "Date de soumission",
    "tenants.title": "Locataires",
    "tenants.active": "Actifs",
    "tenants.total": "Total des locataires",
    "tenants.name": "Nom",
    "tenants.unit": "Unité",
    "tenants.leaseEnd": "Fin du bail",
    "tenants.rentStatus": "Statut du loyer",
    "rent.title": "Perception des loyers",
    "rent.interac": "Virement Interac",
    "rent.stripe": "Carte de crédit/débit",
    "rent.pad": "Prélèvement préautorisé",
    "rent.expected": "Attendu",
    "rent.collected": "Perçu",
    "rent.pending": "En attente",
    "rent.late": "En retard",
    "ltb.title": "Formulaires TAL Québec",
    "ltb.compliant": "Conforme à la loi",
    "ltb.allForms": "Tous les formulaires",
    "ltb.evictionNotices": "Avis d'éviction",
    "ltb.rentIncreases": "Augmentations de loyer",
    "ltb.termination": "Résiliation",
    "ltb.generateForm": "Générer le formulaire",
    "ltb.legalDeadline": "Délai légal",
    "tax.title": "Suivi TPS/TVQ",
    "tax.totalExpenses": "Total des dépenses",
    "tax.hstPaid": "TPS/TVQ payée",
    "tax.deductible": "Dépenses déductibles",
    "tax.ytdTotal": "Total annuel",
    "tax.addExpense": "Ajouter une dépense",
    "tax.craCompliant": "Conforme à l'ARC",
    "lease.title": "Modèles de bail provinciaux",
    "lease.province": "Province",
    "lease.rentGuideline": "Directive d'augmentation",
    "lease.noticeRequired": "Préavis requis",
    "lease.generateLease": "Générer le bail",
    "lease.tenantName": "Nom du locataire",
    "lease.monthlyRent": "Loyer mensuel (CAD)",
    "lease.leaseStart": "Date de début du bail",
    "lease.leaseTerm": "Durée du bail",
    "settings.language": "Langue",
    "settings.english": "English",
    "settings.french": "Français",
    "settings.selectLanguage": "Sélectionner la langue",
    "notifications.title": "Notifications",
    "notifications.center": "Centre de notifications",
    "notifications.unread": "non lues",
    "notifications.urgent": "urgentes",
    "notifications.all": "Toutes",
    "notifications.highPriority": "Haute priorité",
    "notifications.markAllRead": "Tout marquer comme lu",
    "notifications.viewDetails": "Voir les détails",
    "notifications.delete": "Supprimer",
    "notifications.new": "Nouveau",
    "messages.title": "Messages",
    "messages.center": "Centre de messagerie",
    "messages.conversations": "Conversations",
    "messages.search": "Rechercher des conversations...",
    "messages.typeMessage": "Tapez votre message...",
    "messages.sendMessage": "Envoyer",
    "messages.attachFile": "Joindre un fichier",
    "messages.pinned": "Épinglé",
    "messages.starred": "Favoris",
    "messages.tenant": "Locataire",
    "messages.landlord": "Propriétaire",
    "messages.contractor": "Entrepreneur",
    "messages.admin": "Administrateur",
    "reports.title": "Rapports",
    "reports.dashboard": "Tableau de bord des rapports",
    "reports.analytics": "Rapports et analyses",
    "reports.generate": "Générer",
    "reports.download": "Télécharger",
    "reports.financial": "Financiers",
    "reports.occupancy": "Occupation",
    "reports.maintenance": "Entretien",
    "reports.compliance": "Conformité",
    "reports.monthly": "Mensuel",
    "reports.quarterly": "Trimestriel",
    "reports.annual": "Annuel",
    "reports.lastGenerated": "Dernière génération",
    "reports.revenue": "Revenus",
    "reports.expenses": "Dépenses",
    "reports.netIncome": "Revenu net",
    "financial.overview": "Aperçu financier",
    "financial.dashboard": "Tableau financier",
    "financial.totalRevenue": "Revenus totaux",
    "financial.netProfit": "Bénéfice net",
    "financial.totalExpenses": "Dépenses totales",
    "financial.profitMargin": "Marge bénéficiaire",
    "financial.revenueVsExpenses": "Revenus vs dépenses",
    "financial.comparison": "Comparaison sur 12 mois",
    "financial.expenseBreakdown": "Répartition des dépenses",
    "financial.propertyPerformance": "Performance des propriétés",
    "financial.profitability": "Rentabilité par propriété",
    "financial.occupancy": "Occupation",
    "financial.generateInvoice": "Générer une facture",
    "financial.downloadReport": "Télécharger le rapport",
    "financial.scheduleReview": "Planifier un examen",
    "financial.export": "Exporter",
    "financial.lastMonths": "Derniers mois",
    "financial.yearToDate": "Année en cours",
    "contractor.marketplace": "Marché des entrepreneurs",
    "contractor.findContractors": "Trouver des entrepreneurs vérifiés",
    "contractor.allCategories": "Toutes les catégories",
    "contractor.plumbing": "Plomberie",
    "contractor.electrical": "Électricité",
    "contractor.hvac": "CVC",
    "contractor.general": "Général",
    "contractor.painting": "Peinture",
    "contractor.flooring": "Revêtements de sol",
    "contractor.allRatings": "Toutes les notes",
    "contractor.featured": "En vedette",
    "contractor.verified": "Vérifié",
    "contractor.rating": "Note",
    "contractor.reviews": "avis",
    "contractor.completedJobs": "Travaux complétés",
    "contractor.responseTime": "Temps de réponse",
    "contractor.viewProfile": "Voir le profil",
    "contractor.contact": "Contacter",
    "contractor.insurance": "Assuré",
    "contractor.licensed": "Licencié",
    "contractor.backgroundCheck": "Vérification d'antécédents",
  },

  es: {
    "nav.dashboard": "Panel de control",
    "nav.properties": "Propiedades",
    "nav.applications": "Solicitudes",
    "nav.tenants": "Inquilinos",
    "nav.finances": "Finanzas",
    "nav.payments": "Pagos",
    "nav.rentCollection": "Cobro de renta",
    "nav.financialDashboard": "Panel financiero",
    "nav.hstTracker": "Rastreador HST/GST",
    "nav.invoices": "Facturas",
    "nav.operations": "Operaciones",
    "nav.maintenance": "Mantenimiento",
    "nav.documents": "Documentos",
    "nav.ltbForms": "Formularios LTB",
    "nav.leaseTemplates": "Plantillas de arrendamiento",
    "nav.notices": "Avisos",
    "nav.insights": "Análisis",
    "nav.rentalIntelligence": "Inteligencia de alquiler",
    "nav.tenantPassport": "Pasaporte de inquilino",
    "nav.analytics": "Estadísticas",
    "nav.more": "Más",
    "nav.messages": "Mensajes",
    "nav.admin": "Administración",
    "nav.settings": "Configuración",
    "nav.growth": "Crecimiento",
    "nav.listingSyndication": "Sindicación de anuncios",
    "nav.depositFree": "Sin depósito",
    "nav.vendors": "Proveedores",
    "nav.rentCredit": "Crédito de renta",
    "common.search": "Buscar",
    "common.add": "Agregar",
    "common.edit": "Editar",
    "common.delete": "Eliminar",
    "common.save": "Guardar",
    "common.cancel": "Cancelar",
    "common.close": "Cerrar",
    "common.download": "Descargar",
    "common.upload": "Cargar",
    "common.submit": "Enviar",
    "common.back": "Atrás",
    "common.next": "Siguiente",
    "common.previous": "Anterior",
    "common.loading": "Cargando...",
    "common.error": "Error",
    "common.success": "Éxito",
    "common.warning": "Advertencia",
    "common.info": "Información",
    "common.confirm": "Confirmar",
    "common.yes": "Sí",
    "common.no": "No",
    "dashboard.title": "Panel de control",
    "dashboard.welcome": "Bienvenido de nuevo",
    "dashboard.occupancyRate": "Tasa de ocupación",
    "dashboard.monthlyRevenue": "Ingresos mensuales",
    "dashboard.totalProperties": "Total de propiedades",
    "dashboard.pendingApplications": "Solicitudes pendientes",
    "dashboard.recentActivity": "Actividad reciente",
    "dashboard.greeting": "Buenas noches",
    "dashboard.goodMorning": "Buenos días",
    "dashboard.goodAfternoon": "Buenas tardes",
    "dashboard.goodEvening": "Buenas noches",
    "dashboard.applicationsNeedReview": "solicitudes pendientes de revisión",
    "dashboard.overduePayment": "pago vencido",
    "dashboard.revenueThisMonth": "Ingresos este mes",
    "dashboard.vsLastMonth": "vs mes pasado",
    "dashboard.activeProperties": "Propiedades activas",
    "dashboard.vacantUnits": "Unidades vacantes",
    "dashboard.totalUnitsOccupied": "unidades totales · ocupadas",
    "dashboard.alerts": "Alertas",
    "dashboard.aiInsights": "Análisis IA",
    "dashboard.recentApplications": "Solicitudes recientes",
    "dashboard.score": "Puntuación",
    "dashboard.recommendation": "Recomendación",
    "dashboard.approve": "Aprobar",
    "dashboard.review": "Revisar",
    "dashboard.reject": "Rechazar",
    "dashboard.viewApplication": "Ver solicitud",
    "dashboard.propertyPerformance": "Rendimiento de propiedades",
    "dashboard.units": "unidades",
    "dashboard.revenue": "Ingresos",
    "dashboard.riskLevel": "Nivel de riesgo",
    "dashboard.low": "Bajo",
    "dashboard.medium": "Medio",
    "dashboard.high": "Alto",
    "properties.title": "Propiedades",
    "properties.addProperty": "Agregar propiedad",
    "properties.totalUnits": "Total de unidades",
    "properties.occupied": "Ocupadas",
    "properties.vacant": "Vacantes",
    "properties.address": "Dirección",
    "properties.units": "Unidades",
    "properties.monthlyRent": "Renta mensual",
    "applications.title": "Solicitudes",
    "applications.pending": "Pendiente de revisión",
    "applications.approved": "Aprobadas",
    "applications.rejected": "Rechazadas",
    "applications.viewDetails": "Ver detalles",
    "applications.applicantName": "Nombre del solicitante",
    "applications.property": "Propiedad",
    "applications.submittedDate": "Enviada",
    "tenants.title": "Inquilinos",
    "tenants.active": "Activos",
    "tenants.total": "Total de inquilinos",
    "tenants.name": "Nombre",
    "tenants.unit": "Unidad",
    "tenants.leaseEnd": "Fin de contrato",
    "tenants.rentStatus": "Estado de renta",
    "rent.title": "Cobro de renta",
    "rent.interac": "Transferencia Interac",
    "rent.stripe": "Tarjeta de crédito/débito",
    "rent.pad": "Débito preautorizado",
    "rent.expected": "Esperado",
    "rent.collected": "Cobrado",
    "rent.pending": "Pendiente",
    "rent.late": "Atrasado",
    "ltb.title": "Formularios LTB de Ontario",
    "ltb.compliant": "Conforme a la RTA",
    "ltb.allForms": "Todos los formularios",
    "ltb.evictionNotices": "Avisos de desalojo",
    "ltb.rentIncreases": "Aumentos de renta",
    "ltb.termination": "Terminación",
    "ltb.generateForm": "Generar formulario",
    "ltb.legalDeadline": "Plazo legal",
    "tax.title": "Rastreador HST/GST",
    "tax.totalExpenses": "Total de gastos",
    "tax.hstPaid": "HST/GST pagado",
    "tax.deductible": "Gastos deducibles",
    "tax.ytdTotal": "Total del año",
    "tax.addExpense": "Agregar gasto",
    "tax.craCompliant": "Conforme a la CRA",
    "lease.title": "Plantillas de arrendamiento provincial",
    "lease.province": "Provincia",
    "lease.rentGuideline": "Directriz de aumento de renta",
    "lease.noticeRequired": "Aviso requerido",
    "lease.generateLease": "Generar contrato",
    "lease.tenantName": "Nombre del inquilino",
    "lease.monthlyRent": "Renta mensual (CAD)",
    "lease.leaseStart": "Fecha de inicio del contrato",
    "lease.leaseTerm": "Duración del contrato",
    "settings.language": "Idioma",
    "settings.english": "English",
    "settings.french": "Français",
    "settings.selectLanguage": "Seleccionar idioma",
    "notifications.title": "Notificaciones",
    "notifications.center": "Centro de notificaciones",
    "notifications.unread": "no leídas",
    "notifications.urgent": "urgentes",
    "notifications.all": "Todas",
    "notifications.highPriority": "Alta prioridad",
    "notifications.markAllRead": "Marcar todas como leídas",
    "notifications.viewDetails": "Ver detalles",
    "notifications.delete": "Eliminar",
    "notifications.new": "Nuevo",
    "messages.title": "Mensajes",
    "messages.center": "Centro de mensajes",
    "messages.conversations": "Conversaciones",
    "messages.search": "Buscar conversaciones...",
    "messages.typeMessage": "Escribe tu mensaje...",
    "messages.sendMessage": "Enviar",
    "messages.attachFile": "Adjuntar archivo",
    "messages.pinned": "Fijado",
    "messages.starred": "Destacado",
    "messages.tenant": "Inquilino",
    "messages.landlord": "Propietario",
    "messages.contractor": "Contratista",
    "messages.admin": "Administrador",
    "reports.title": "Informes",
    "reports.dashboard": "Panel de informes",
    "reports.analytics": "Informes y análisis",
    "reports.generate": "Generar",
    "reports.download": "Descargar",
    "reports.financial": "Financiero",
    "reports.occupancy": "Ocupación",
    "reports.maintenance": "Mantenimiento",
    "reports.compliance": "Cumplimiento",
    "reports.monthly": "Mensual",
    "reports.quarterly": "Trimestral",
    "reports.annual": "Anual",
    "reports.lastGenerated": "Última generación",
    "reports.revenue": "Ingresos",
    "reports.expenses": "Gastos",
    "reports.netIncome": "Ingresos netos",
    "financial.overview": "Resumen financiero",
    "financial.dashboard": "Panel financiero",
    "financial.totalRevenue": "Ingresos totales",
    "financial.netProfit": "Beneficio neto",
    "financial.totalExpenses": "Gastos totales",
    "financial.profitMargin": "Margen de beneficio",
    "financial.revenueVsExpenses": "Ingresos vs gastos",
    "financial.comparison": "Comparación de 12 meses",
    "financial.expenseBreakdown": "Desglose de gastos",
    "financial.propertyPerformance": "Rendimiento de propiedades",
    "financial.profitability": "Rentabilidad por propiedad",
    "financial.occupancy": "Ocupación",
    "financial.generateInvoice": "Generar factura",
    "financial.downloadReport": "Descargar informe",
    "financial.scheduleReview": "Programar revisión",
    "financial.export": "Exportar",
    "financial.lastMonths": "Últimos meses",
    "financial.yearToDate": "Año hasta la fecha",
    "contractor.marketplace": "Mercado de contratistas",
    "contractor.findContractors": "Encontrar contratistas verificados",
    "contractor.allCategories": "Todas las categorías",
    "contractor.plumbing": "Plomería",
    "contractor.electrical": "Electricidad",
    "contractor.hvac": "HVAC",
    "contractor.general": "General",
    "contractor.painting": "Pintura",
    "contractor.flooring": "Pisos",
    "contractor.allRatings": "Todas las calificaciones",
    "contractor.featured": "Destacado",
    "contractor.verified": "Verificado",
    "contractor.rating": "Calificación",
    "contractor.reviews": "reseñas",
    "contractor.completedJobs": "Trabajos completados",
    "contractor.responseTime": "Tiempo de respuesta",
    "contractor.viewProfile": "Ver perfil",
    "contractor.contact": "Contactar",
    "contractor.insurance": "Asegurado",
    "contractor.licensed": "Con licencia",
    "contractor.backgroundCheck": "Verificación de antecedentes",
  },

  zh: {
    "nav.dashboard": "控制台",
    "nav.properties": "房产",
    "nav.applications": "申请",
    "nav.tenants": "租客",
    "nav.finances": "财务",
    "nav.payments": "付款",
    "nav.rentCollection": "租金收取",
    "nav.financialDashboard": "财务仪表板",
    "nav.hstTracker": "HST/GST 追踪",
    "nav.invoices": "发票",
    "nav.operations": "运营",
    "nav.maintenance": "维护",
    "nav.documents": "文件",
    "nav.ltbForms": "LTB 表格",
    "nav.leaseTemplates": "租约模板",
    "nav.notices": "通知",
    "nav.insights": "洞察",
    "nav.rentalIntelligence": "租赁智能",
    "nav.tenantPassport": "租客护照",
    "nav.analytics": "数据分析",
    "nav.more": "更多",
    "nav.messages": "消息",
    "nav.admin": "管理",
    "nav.settings": "设置",
    "nav.growth": "增长",
    "nav.listingSyndication": "房源联合",
    "nav.depositFree": "免押金",
    "nav.vendors": "供应商",
    "nav.rentCredit": "租金信用",
    "common.search": "搜索",
    "common.add": "添加",
    "common.edit": "编辑",
    "common.delete": "删除",
    "common.save": "保存",
    "common.cancel": "取消",
    "common.close": "关闭",
    "common.download": "下载",
    "common.upload": "上传",
    "common.submit": "提交",
    "common.back": "返回",
    "common.next": "下一步",
    "common.previous": "上一步",
    "common.loading": "加载中...",
    "common.error": "错误",
    "common.success": "成功",
    "common.warning": "警告",
    "common.info": "信息",
    "common.confirm": "确认",
    "common.yes": "是",
    "common.no": "否",
    "dashboard.title": "控制台",
    "dashboard.welcome": "欢迎回来",
    "dashboard.occupancyRate": "入住率",
    "dashboard.monthlyRevenue": "月收入",
    "dashboard.totalProperties": "总房产数",
    "dashboard.pendingApplications": "待审申请",
    "dashboard.recentActivity": "最近活动",
    "dashboard.greeting": "晚上好",
    "dashboard.goodMorning": "早上好",
    "dashboard.goodAfternoon": "下午好",
    "dashboard.goodEvening": "晚上好",
    "dashboard.applicationsNeedReview": "申请需要审核",
    "dashboard.overduePayment": "逾期付款",
    "dashboard.revenueThisMonth": "本月收入",
    "dashboard.vsLastMonth": "对比上月",
    "dashboard.activeProperties": "活跃房产",
    "dashboard.vacantUnits": "空置单元",
    "dashboard.totalUnitsOccupied": "总单元 · 已占",
    "dashboard.alerts": "警报",
    "dashboard.aiInsights": "AI 洞察",
    "dashboard.recentApplications": "最近申请",
    "dashboard.score": "评分",
    "dashboard.recommendation": "建议",
    "dashboard.approve": "批准",
    "dashboard.review": "审核",
    "dashboard.reject": "拒绝",
    "dashboard.viewApplication": "查看申请",
    "dashboard.propertyPerformance": "房产表现",
    "dashboard.units": "单元",
    "dashboard.revenue": "收入",
    "dashboard.riskLevel": "风险等级",
    "dashboard.low": "低",
    "dashboard.medium": "中",
    "dashboard.high": "高",
    "properties.title": "房产",
    "properties.addProperty": "添加房产",
    "properties.totalUnits": "总单元数",
    "properties.occupied": "已占用",
    "properties.vacant": "空置",
    "properties.address": "地址",
    "properties.units": "单元",
    "properties.monthlyRent": "月租金",
    "applications.title": "申请",
    "applications.pending": "待审核",
    "applications.approved": "已批准",
    "applications.rejected": "已拒绝",
    "applications.viewDetails": "查看详情",
    "applications.applicantName": "申请人姓名",
    "applications.property": "房产",
    "applications.submittedDate": "提交日期",
    "tenants.title": "租客",
    "tenants.active": "活跃",
    "tenants.total": "总租客数",
    "tenants.name": "姓名",
    "tenants.unit": "单元",
    "tenants.leaseEnd": "租约到期",
    "tenants.rentStatus": "租金状态",
    "rent.title": "租金收取",
    "rent.interac": "Interac 转账",
    "rent.stripe": "信用卡/借记卡",
    "rent.pad": "预授权扣款",
    "rent.expected": "应收",
    "rent.collected": "已收",
    "rent.pending": "待处理",
    "rent.late": "逾期",
    "ltb.title": "安大略 LTB 表格",
    "ltb.compliant": "符合 RTA",
    "ltb.allForms": "所有表格",
    "ltb.evictionNotices": "驱逐通知",
    "ltb.rentIncreases": "租金上涨",
    "ltb.termination": "终止",
    "ltb.generateForm": "生成表格",
    "ltb.legalDeadline": "法律期限",
    "tax.title": "HST/GST 追踪",
    "tax.totalExpenses": "总支出",
    "tax.hstPaid": "已付 HST/GST",
    "tax.deductible": "可抵扣支出",
    "tax.ytdTotal": "年初至今总计",
    "tax.addExpense": "添加支出",
    "tax.craCompliant": "符合 CRA",
    "lease.title": "省级租约模板",
    "lease.province": "省份",
    "lease.rentGuideline": "租金上涨指导方针",
    "lease.noticeRequired": "所需通知",
    "lease.generateLease": "生成租约",
    "lease.tenantName": "租客姓名",
    "lease.monthlyRent": "月租金 (CAD)",
    "lease.leaseStart": "租约开始日期",
    "lease.leaseTerm": "租约期限",
    "settings.language": "语言",
    "settings.english": "English",
    "settings.french": "Français",
    "settings.selectLanguage": "选择语言",
    "notifications.title": "通知",
    "notifications.center": "通知中心",
    "notifications.unread": "未读",
    "notifications.urgent": "紧急",
    "notifications.all": "全部",
    "notifications.highPriority": "高优先级",
    "notifications.markAllRead": "全部标为已读",
    "notifications.viewDetails": "查看详情",
    "notifications.delete": "删除",
    "notifications.new": "新",
    "messages.title": "消息",
    "messages.center": "消息中心",
    "messages.conversations": "对话",
    "messages.search": "搜索对话...",
    "messages.typeMessage": "输入消息...",
    "messages.sendMessage": "发送",
    "messages.attachFile": "附加文件",
    "messages.pinned": "已固定",
    "messages.starred": "已收藏",
    "messages.tenant": "租客",
    "messages.landlord": "房东",
    "messages.contractor": "承包商",
    "messages.admin": "管理员",
    "reports.title": "报告",
    "reports.dashboard": "报告面板",
    "reports.analytics": "报告与分析",
    "reports.generate": "生成",
    "reports.download": "下载",
    "reports.financial": "财务",
    "reports.occupancy": "入住率",
    "reports.maintenance": "维护",
    "reports.compliance": "合规",
    "reports.monthly": "月度",
    "reports.quarterly": "季度",
    "reports.annual": "年度",
    "reports.lastGenerated": "最后生成",
    "reports.revenue": "收入",
    "reports.expenses": "支出",
    "reports.netIncome": "净收入",
    "financial.overview": "财务概览",
    "financial.dashboard": "财务仪表板",
    "financial.totalRevenue": "总收入",
    "financial.netProfit": "净利润",
    "financial.totalExpenses": "总支出",
    "financial.profitMargin": "利润率",
    "financial.revenueVsExpenses": "收入与支出",
    "financial.comparison": "12个月对比",
    "financial.expenseBreakdown": "支出明细",
    "financial.propertyPerformance": "房产表现",
    "financial.profitability": "各房产盈利能力",
    "financial.occupancy": "入住率",
    "financial.generateInvoice": "生成发票",
    "financial.downloadReport": "下载报告",
    "financial.scheduleReview": "安排审查",
    "financial.export": "导出",
    "financial.lastMonths": "过去几个月",
    "financial.yearToDate": "年初至今",
    "contractor.marketplace": "承包商市场",
    "contractor.findContractors": "寻找经过验证的承包商",
    "contractor.allCategories": "所有类别",
    "contractor.plumbing": "管道",
    "contractor.electrical": "电气",
    "contractor.hvac": "暖通空调",
    "contractor.general": "通用",
    "contractor.painting": "油漆",
    "contractor.flooring": "地板",
    "contractor.allRatings": "所有评级",
    "contractor.featured": "特色",
    "contractor.verified": "已验证",
    "contractor.rating": "评级",
    "contractor.reviews": "评论",
    "contractor.completedJobs": "完成工作",
    "contractor.responseTime": "响应时间",
    "contractor.viewProfile": "查看资料",
    "contractor.contact": "联系",
    "contractor.insurance": "已投保",
    "contractor.licensed": "已持牌",
    "contractor.backgroundCheck": "背景调查",
  },

  pa: {
    "nav.dashboard": "ਡੈਸ਼ਬੋਰਡ",
    "nav.properties": "ਜਾਇਦਾਦਾਂ",
    "nav.applications": "ਅਰਜ਼ੀਆਂ",
    "nav.tenants": "ਕਿਰਾਏਦਾਰ",
    "nav.finances": "ਵਿੱਤ",
    "nav.payments": "ਭੁਗਤਾਨ",
    "nav.rentCollection": "ਕਿਰਾਇਆ ਉਗਰਾਹੀ",
    "nav.financialDashboard": "ਵਿੱਤੀ ਡੈਸ਼ਬੋਰਡ",
    "nav.hstTracker": "HST/GST ਟਰੈਕਰ",
    "nav.invoices": "ਬਿੱਲ",
    "nav.operations": "ਕਾਰਵਾਈਆਂ",
    "nav.maintenance": "ਦੇਖਭਾਲ",
    "nav.documents": "ਦਸਤਾਵੇਜ਼",
    "nav.ltbForms": "LTB ਫਾਰਮ",
    "nav.leaseTemplates": "ਲੀਜ਼ ਟੈਂਪਲੇਟ",
    "nav.notices": "ਨੋਟਿਸ",
    "nav.insights": "ਜਾਣਕਾਰੀ",
    "nav.rentalIntelligence": "ਕਿਰਾਇਆ ਬੁੱਧੀਮੱਤਾ",
    "nav.tenantPassport": "ਕਿਰਾਏਦਾਰ ਪਾਸਪੋਰਟ",
    "nav.analytics": "ਵਿਸ਼ਲੇਸ਼ਣ",
    "nav.more": "ਹੋਰ",
    "nav.messages": "ਸੁਨੇਹੇ",
    "nav.admin": "ਪ੍ਰਸ਼ਾਸਨ",
    "nav.settings": "ਸੈਟਿੰਗਾਂ",
    "nav.growth": "ਵਿਕਾਸ",
    "nav.listingSyndication": "ਲਿਸਟਿੰਗ ਸਿੰਡੀਕੇਸ਼ਨ",
    "nav.depositFree": "ਜਮ੍ਹਾਂ ਰਕਮ ਮੁਕਤ",
    "nav.vendors": "ਵਿਕਰੇਤਾ",
    "nav.rentCredit": "ਕਿਰਾਇਆ ਕ੍ਰੈਡਿਟ",
    "common.search": "ਖੋਜੋ",
    "common.add": "ਸ਼ਾਮਲ ਕਰੋ",
    "common.edit": "ਸੰਪਾਦਿਤ ਕਰੋ",
    "common.delete": "ਮਿਟਾਓ",
    "common.save": "ਸੁਰੱਖਿਅਤ ਕਰੋ",
    "common.cancel": "ਰੱਦ ਕਰੋ",
    "common.close": "ਬੰਦ ਕਰੋ",
    "common.download": "ਡਾਊਨਲੋਡ ਕਰੋ",
    "common.upload": "ਅਪਲੋਡ ਕਰੋ",
    "common.submit": "ਜਮ੍ਹਾਂ ਕਰੋ",
    "common.back": "ਪਿੱਛੇ",
    "common.next": "ਅੱਗੇ",
    "common.previous": "ਪਿਛਲਾ",
    "common.loading": "ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...",
    "common.error": "ਗਲਤੀ",
    "common.success": "ਸਫਲ",
    "common.warning": "ਚੇਤਾਵਨੀ",
    "common.info": "ਜਾਣਕਾਰੀ",
    "common.confirm": "ਪੁਸ਼ਟੀ ਕਰੋ",
    "common.yes": "ਹਾਂ",
    "common.no": "ਨਹੀਂ",
    "dashboard.title": "ਡੈਸ਼ਬੋਰਡ",
    "dashboard.welcome": "ਵਾਪਸ ਆਓ",
    "dashboard.occupancyRate": "ਰਿਹਾਇਸ਼ੀ ਦਰ",
    "dashboard.monthlyRevenue": "ਮਾਸਿਕ ਆਮਦਨ",
    "dashboard.totalProperties": "ਕੁੱਲ ਜਾਇਦਾਦਾਂ",
    "dashboard.pendingApplications": "ਲੰਬਿਤ ਅਰਜ਼ੀਆਂ",
    "dashboard.recentActivity": "ਹਾਲੀਆ ਗਤੀਵਿਧੀ",
    "dashboard.greeting": "ਸ਼ੁਭ ਸ਼ਾਮ",
    "dashboard.goodMorning": "ਸ਼ੁਭ ਸਵੇਰ",
    "dashboard.goodAfternoon": "ਸ਼ੁਭ ਦੁਪਹਿਰ",
    "dashboard.goodEvening": "ਸ਼ੁਭ ਸ਼ਾਮ",
    "dashboard.applicationsNeedReview": "ਅਰਜ਼ੀਆਂ ਦੀ ਸਮੀਖਿਆ ਦੀ ਲੋੜ",
    "dashboard.overduePayment": "ਬਕਾਇਆ ਭੁਗਤਾਨ",
    "dashboard.revenueThisMonth": "ਇਸ ਮਹੀਨੇ ਆਮਦਨ",
    "dashboard.vsLastMonth": "ਪਿਛਲੇ ਮਹੀਨੇ ਦੇ ਮੁਕਾਬਲੇ",
    "dashboard.activeProperties": "ਸਰਗਰਮ ਜਾਇਦਾਦਾਂ",
    "dashboard.vacantUnits": "ਖਾਲੀ ਯੂਨਿਟ",
    "dashboard.totalUnitsOccupied": "ਕੁੱਲ ਯੂਨਿਟ · ਕਬਜ਼ੇ ਵਿੱਚ",
    "dashboard.alerts": "ਚੇਤਾਵਨੀਆਂ",
    "dashboard.aiInsights": "AI ਜਾਣਕਾਰੀ",
    "dashboard.recentApplications": "ਹਾਲੀਆ ਅਰਜ਼ੀਆਂ",
    "dashboard.score": "ਸਕੋਰ",
    "dashboard.recommendation": "ਸਿਫਾਰਸ਼",
    "dashboard.approve": "ਮਨਜ਼ੂਰ ਕਰੋ",
    "dashboard.review": "ਸਮੀਖਿਆ ਕਰੋ",
    "dashboard.reject": "ਰੱਦ ਕਰੋ",
    "dashboard.viewApplication": "ਅਰਜ਼ੀ ਵੇਖੋ",
    "dashboard.propertyPerformance": "ਜਾਇਦਾਦ ਪ੍ਰਦਰਸ਼ਨ",
    "dashboard.units": "ਯੂਨਿਟ",
    "dashboard.revenue": "ਆਮਦਨ",
    "dashboard.riskLevel": "ਜੋਖਮ ਪੱਧਰ",
    "dashboard.low": "ਘੱਟ",
    "dashboard.medium": "ਮੱਧਮ",
    "dashboard.high": "ਉੱਚ",
    "properties.title": "ਜਾਇਦਾਦਾਂ",
    "properties.addProperty": "ਜਾਇਦਾਦ ਸ਼ਾਮਲ ਕਰੋ",
    "properties.totalUnits": "ਕੁੱਲ ਯੂਨਿਟ",
    "properties.occupied": "ਕਬਜ਼ੇ ਵਿੱਚ",
    "properties.vacant": "ਖਾਲੀ",
    "properties.address": "ਪਤਾ",
    "properties.units": "ਯੂਨਿਟ",
    "properties.monthlyRent": "ਮਾਸਿਕ ਕਿਰਾਇਆ",
    "applications.title": "ਅਰਜ਼ੀਆਂ",
    "applications.pending": "ਸਮੀਖਿਆ ਲੰਬਿਤ",
    "applications.approved": "ਮਨਜ਼ੂਰ",
    "applications.rejected": "ਰੱਦ",
    "applications.viewDetails": "ਵੇਰਵੇ ਵੇਖੋ",
    "applications.applicantName": "ਅਰਜ਼ੀਦਾਰ ਦਾ ਨਾਮ",
    "applications.property": "ਜਾਇਦਾਦ",
    "applications.submittedDate": "ਜਮ੍ਹਾਂ ਕੀਤੀ",
    "tenants.title": "ਕਿਰਾਏਦਾਰ",
    "tenants.active": "ਸਰਗਰਮ",
    "tenants.total": "ਕੁੱਲ ਕਿਰਾਏਦਾਰ",
    "tenants.name": "ਨਾਮ",
    "tenants.unit": "ਯੂਨਿਟ",
    "tenants.leaseEnd": "ਲੀਜ਼ ਸਮਾਪਤੀ",
    "tenants.rentStatus": "ਕਿਰਾਇਆ ਸਥਿਤੀ",
    "rent.title": "ਕਿਰਾਇਆ ਉਗਰਾਹੀ",
    "rent.interac": "Interac ਤਬਾਦਲਾ",
    "rent.stripe": "ਕ੍ਰੈਡਿਟ/ਡੈਬਿਟ ਕਾਰਡ",
    "rent.pad": "ਪ੍ਰੀ-ਅਧਿਕਾਰਿਤ ਡੈਬਿਟ",
    "rent.expected": "ਉਮੀਦ",
    "rent.collected": "ਇਕੱਤਰ",
    "rent.pending": "ਲੰਬਿਤ",
    "rent.late": "ਦੇਰੀ",
    "ltb.title": "ਓਨਟਾਰੀਓ LTB ਫਾਰਮ",
    "ltb.compliant": "RTA ਅਨੁਸਾਰ",
    "ltb.allForms": "ਸਾਰੇ ਫਾਰਮ",
    "ltb.evictionNotices": "ਬੇਦਖਲੀ ਨੋਟਿਸ",
    "ltb.rentIncreases": "ਕਿਰਾਇਆ ਵਾਧਾ",
    "ltb.termination": "ਸਮਾਪਤੀ",
    "ltb.generateForm": "ਫਾਰਮ ਬਣਾਓ",
    "ltb.legalDeadline": "ਕਾਨੂੰਨੀ ਸਮਾਂ ਸੀਮਾ",
    "tax.title": "HST/GST ਟਰੈਕਰ",
    "tax.totalExpenses": "ਕੁੱਲ ਖਰਚੇ",
    "tax.hstPaid": "HST/GST ਅਦਾ",
    "tax.deductible": "ਕਟੌਤੀਯੋਗ ਖਰਚੇ",
    "tax.ytdTotal": "ਸਾਲ ਤੋਂ ਕੁੱਲ",
    "tax.addExpense": "ਖਰਚਾ ਸ਼ਾਮਲ ਕਰੋ",
    "tax.craCompliant": "CRA ਅਨੁਸਾਰ",
    "lease.title": "ਸੂਬਾਈ ਲੀਜ਼ ਟੈਂਪਲੇਟ",
    "lease.province": "ਸੂਬਾ",
    "lease.rentGuideline": "ਕਿਰਾਇਆ ਵਾਧਾ ਗਾਈਡਲਾਈਨ",
    "lease.noticeRequired": "ਲੋੜੀਂਦਾ ਨੋਟਿਸ",
    "lease.generateLease": "ਲੀਜ਼ ਬਣਾਓ",
    "lease.tenantName": "ਕਿਰਾਏਦਾਰ ਦਾ ਨਾਮ",
    "lease.monthlyRent": "ਮਾਸਿਕ ਕਿਰਾਇਆ (CAD)",
    "lease.leaseStart": "ਲੀਜ਼ ਸ਼ੁਰੂ ਹੋਣ ਦੀ ਮਿਤੀ",
    "lease.leaseTerm": "ਲੀਜ਼ ਮਿਆਦ",
    "settings.language": "ਭਾਸ਼ਾ",
    "settings.english": "English",
    "settings.french": "Français",
    "settings.selectLanguage": "ਭਾਸ਼ਾ ਚੁਣੋ",
    "notifications.title": "ਸੂਚਨਾਵਾਂ",
    "notifications.center": "ਸੂਚਨਾ ਕੇਂਦਰ",
    "notifications.unread": "ਅਣਪੜ੍ਹੀਆਂ",
    "notifications.urgent": "ਜ਼ਰੂਰੀ",
    "notifications.all": "ਸਾਰੀਆਂ",
    "notifications.highPriority": "ਉੱਚ ਪ੍ਰਾਥਮਿਕਤਾ",
    "notifications.markAllRead": "ਸਭ ਨੂੰ ਪੜ੍ਹਿਆ ਮਾਰਕ ਕਰੋ",
    "notifications.viewDetails": "ਵੇਰਵੇ ਵੇਖੋ",
    "notifications.delete": "ਮਿਟਾਓ",
    "notifications.new": "ਨਵਾਂ",
    "messages.title": "ਸੁਨੇਹੇ",
    "messages.center": "ਸੁਨੇਹਾ ਕੇਂਦਰ",
    "messages.conversations": "ਗੱਲਬਾਤ",
    "messages.search": "ਗੱਲਬਾਤ ਖੋਜੋ...",
    "messages.typeMessage": "ਆਪਣਾ ਸੁਨੇਹਾ ਟਾਈਪ ਕਰੋ...",
    "messages.sendMessage": "ਭੇਜੋ",
    "messages.attachFile": "ਫਾਇਲ ਜੋੜੋ",
    "messages.pinned": "ਪਿੰਨ ਕੀਤਾ",
    "messages.starred": "ਤਾਰਾਂਕਿਤ",
    "messages.tenant": "ਕਿਰਾਏਦਾਰ",
    "messages.landlord": "ਮਕਾਨ ਮਾਲਕ",
    "messages.contractor": "ਠੇਕੇਦਾਰ",
    "messages.admin": "ਪ੍ਰਸ਼ਾਸਕ",
    "reports.title": "ਰਿਪੋਰਟਾਂ",
    "reports.dashboard": "ਰਿਪੋਰਟ ਡੈਸ਼ਬੋਰਡ",
    "reports.analytics": "ਰਿਪੋਰਟਾਂ ਅਤੇ ਵਿਸ਼ਲੇਸ਼ਣ",
    "reports.generate": "ਬਣਾਓ",
    "reports.download": "ਡਾਊਨਲੋਡ ਕਰੋ",
    "reports.financial": "ਵਿੱਤੀ",
    "reports.occupancy": "ਕਬਜ਼ਾ",
    "reports.maintenance": "ਦੇਖਭਾਲ",
    "reports.compliance": "ਅਨੁਪਾਲਨ",
    "reports.monthly": "ਮਾਸਿਕ",
    "reports.quarterly": "ਤਿਮਾਹੀ",
    "reports.annual": "ਸਾਲਾਨਾ",
    "reports.lastGenerated": "ਆਖਰੀ ਵਾਰ ਬਣਾਈ",
    "reports.revenue": "ਆਮਦਨ",
    "reports.expenses": "ਖਰਚੇ",
    "reports.netIncome": "ਸ਼ੁੱਧ ਆਮਦਨ",
    "financial.overview": "ਵਿੱਤੀ ਸੰਖੇਪ",
    "financial.dashboard": "ਵਿੱਤੀ ਡੈਸ਼ਬੋਰਡ",
    "financial.totalRevenue": "ਕੁੱਲ ਆਮਦਨ",
    "financial.netProfit": "ਸ਼ੁੱਧ ਮੁਨਾਫ਼ਾ",
    "financial.totalExpenses": "ਕੁੱਲ ਖਰਚੇ",
    "financial.profitMargin": "ਮੁਨਾਫ਼ਾ ਮਾਰਜਿਨ",
    "financial.revenueVsExpenses": "ਆਮਦਨ ਬਨਾਮ ਖਰਚੇ",
    "financial.comparison": "12 ਮਹੀਨੇ ਦੀ ਤੁਲਨਾ",
    "financial.expenseBreakdown": "ਖਰਚਾ ਵੇਰਵਾ",
    "financial.propertyPerformance": "ਜਾਇਦਾਦ ਪ੍ਰਦਰਸ਼ਨ",
    "financial.profitability": "ਜਾਇਦਾਦ ਅਨੁਸਾਰ ਮੁਨਾਫ਼ਾ",
    "financial.occupancy": "ਕਬਜ਼ਾ",
    "financial.generateInvoice": "ਬਿੱਲ ਬਣਾਓ",
    "financial.downloadReport": "ਰਿਪੋਰਟ ਡਾਊਨਲੋਡ ਕਰੋ",
    "financial.scheduleReview": "ਸਮੀਖਿਆ ਨਿਯਤ ਕਰੋ",
    "financial.export": "ਨਿਰਯਾਤ ਕਰੋ",
    "financial.lastMonths": "ਪਿਛਲੇ ਮਹੀਨੇ",
    "financial.yearToDate": "ਸਾਲ ਤੋਂ ਲੈ ਕੇ",
    "contractor.marketplace": "ਠੇਕੇਦਾਰ ਬਾਜ਼ਾਰ",
    "contractor.findContractors": "ਪ੍ਰਮਾਣਿਤ ਠੇਕੇਦਾਰ ਲੱਭੋ",
    "contractor.allCategories": "ਸਾਰੀਆਂ ਸ਼੍ਰੇਣੀਆਂ",
    "contractor.plumbing": "ਪਲੰਬਿੰਗ",
    "contractor.electrical": "ਬਿਜਲੀ",
    "contractor.hvac": "HVAC",
    "contractor.general": "ਆਮ",
    "contractor.painting": "ਰੰਗ-ਰੋਗਨ",
    "contractor.flooring": "ਫਲੋਰਿੰਗ",
    "contractor.allRatings": "ਸਾਰੀਆਂ ਰੇਟਿੰਗਾਂ",
    "contractor.featured": "ਵਿਸ਼ੇਸ਼",
    "contractor.verified": "ਪ੍ਰਮਾਣਿਤ",
    "contractor.rating": "ਰੇਟਿੰਗ",
    "contractor.reviews": "ਸਮੀਖਿਆਵਾਂ",
    "contractor.completedJobs": "ਪੂਰੇ ਕੰਮ",
    "contractor.responseTime": "ਜਵਾਬ ਸਮਾਂ",
    "contractor.viewProfile": "ਪ੍ਰੋਫਾਈਲ ਵੇਖੋ",
    "contractor.contact": "ਸੰਪਰਕ ਕਰੋ",
    "contractor.insurance": "ਬੀਮਾ",
    "contractor.licensed": "ਲਾਇਸੈਂਸਧਾਰੀ",
    "contractor.backgroundCheck": "ਪਿਛੋਕੜ ਜਾਂਚ",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem("kaya-language");
    return (saved as Language) || "en";
  });

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem("kaya-language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations["en"][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
